### ISSUE TITLE
CLEO Status Screen: Add Astrid Script Info

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/cleo_web#11]
The Status screen would be more useful if it included information about what's currently happening in Astrid. This information can be pulled out of the Astrid database.

GBO already has a Django app for this database. Once you have that installed, you will be able to query the Astrid database via the models it provides.

The "current script" is the most recently executed `History` row (`History.datetime`) that is in the "In Progress" state (`History.executed_state`). In whatever format you think is most useful, please display the following information about the current script:

- The current observer (`ObsProcedure.observer`) and operator (`ObsProcedure.operator`)
- The current script itself (`History.executed_script`)
- The status of the script (`History.status`)
- The log file (`History.log`)
- The Project (`ObsProjectRef.name`) and Script name (`ObsProcedure.name`)

If you come across more useful information, feel free to include that as well! It's up to you

**Comment by sofiarobertson** [comment]
commit 92792f80144804f0eb024b3c9e1095dfd5853e91
