### ISSUE TITLE
Managers with minor managers should be indicated

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/cleo_web#12]
In CLEO, major manager names are indicated in blue if they contain minor managers. Something similar should be done for CLEO Web Device Explorer

**Comment by sofiarobertson** [comment]
commit a282d6de8a209612ec753486d3211062cbb8be05 



![Image](https://github.com/GreenBankObservatory/cleo_web/assets/171201597/c8066a2f-f399-4888-b2a8-777ffe575855)
