### ISSUE TITLE
Value field of currently-selected parameter should update in real time

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/cleo_web#14]
Use HTMX to introduce dynamic behavior to the Device Explorer. Once per second, the current value of the currently-selected parameter should be retrieved from Chalice. The new value should then be rendered in place of the old one.

The page should not look any different than before; the only functional change is that once per second the value might change

This will require the creation of an additional view and URL.

To get an overview of what HTMX is and how to use it, start here: https://htmx.org/docs/

For now you can use [the CDN](https://htmx.org/docs/#via-a-cdn-e-g-unpkg-com) to "install" HTMX

**Comment by sofiarobertson** [comment]
commit c306ec700c180f614fd71840c00441d02571cb4a

**Comment by sofiarobertson** [comment]
dynamic sampler values: commit 97a3c200f8a155c1b5e2a4cdeec1afae580c5470
