### ISSUE TITLE
Determine the selected manager based on URL parameter

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/cleo_web#3]
`/devex` should now determine the selected manager based on a URL parameter. For example, `/devex/?manager=ScanCoordinator` would result in `ScanCoordinator.ScanCoordinator` being selected

Here's some docs on this: https://docs.djangoproject.com/en/5.0/ref/request-response/#django.http.QueryDict

You should end up with code similar to `manager = request.GET.get("manager", None)`

Additionally, every item in the left panel should be a link, so that they can be clicked on (which selects a Manager), and then the second column will update to reflect the newly-selected Manager

For reference, here's the area we are trying to replicate here: 
![Paste](https://github.com/GreenBankObservatory/cleo_web/assets/2555049/da184bfa-9931-4069-af23-5295602e3a3f)

**Comment by sofiarobertson** [comment]
commit 0c091ed15f9278629e560c3c1289c40c246abff4 

![Image](https://github.com/GreenBankObservatory/cleo_web/assets/171201597/9931139a-ec0c-4548-9290-fbfcdb9ab641)
