### ISSUE TITLE
Selected Manager should be indicated visually

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/cleo_web#4]
If `/devex` is showing a Selected Manager, that Manager's item in the left column should be indicated with a background color

For reference (don't include red border; that is just to indicate relevant region)

![Image](https://github.com/GreenBankObservatory/cleo_web/assets/2555049/f3e79de8-14f3-4f45-a526-204b188ad7f6)

This will probably require some sort of conditional in the template. A common pattern would involve something like:

```html
{% for manager in ... %}
<li {% if manager == selected_manager %}class=bg-primary{% endif %}>...</li>
...

```

Where `selected_manager` is whatever is passed in via the view (as context), and (probably) determined based on `manager` URL param

See Bootstrap docs for more on colors:

- https://getbootstrap.com/docs/5.3/utilities/colors/#colors
- https://getbootstrap.com/docs/5.3/helpers/color-background/
- https://getbootstrap.com/docs/5.3/utilities/background/

**Comment by sofiarobertson** [comment]
commit 5976a212dfce4982632d4be8b3ff5b04f4e225c0

![Image](https://github.com/GreenBankObservatory/cleo_web/assets/171201597/ffeaf48b-f2b7-47f7-944a-46c52737430c)

(I updated the title of the column, and got rid of the underlined links after this commit. It will be shown in the next one.)
