### ISSUE TITLE
Add third column to Device Explorer that shows Selected Parameter

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/cleo_web#5]
1. Whatever item is selected in the Parameter Column is the "Selected Parameter"
2. Add a third column to Device Explorer that shows contents of this Selected Parameter
3. Selected Parameter should be indicated visually in the Parameter Column  in the same style as #4 
4. New third column should have two rows:
    - Parameter Fields
    - Attributes
 

Should be very similar to this column:

![Image](https://github.com/GreenBankObservatory/cleo_web/assets/2555049/c51f887a-035c-44cb-81c2-36a6e80ec397)

**Comment by sofiarobertson** [comment]
commit 88acbd66c551d763cb2b239284ecf42cfb2096bd

![Image](https://github.com/GreenBankObservatory/cleo_web/assets/171201597/b54c26fc-9fff-4be8-a368-b71427aac569)

**Comment by tchamberlin** [comment]
Could you break the `value` field out into its own row, with a blue background similar to what is in CLEO?

**Comment by tchamberlin** [comment]
Also don't use `<p>` tag for column contents. These should be `<li>`, inside of a `<ul>`. To avoid bullet points from being rendered, set a class on the `<ul>`:

```html
<ul class="list-unstyled">
   <li>...</li>
</ul>
```

**Comment by sofiarobertson** [comment]
commit d331093d33a5c9cd0185621ff39d0d66e33ed23a
