### ISSUE TITLE
Manager list should be a tree structure

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/cleo_web#7]
In CLEO Device Explorer, "major" managers contain "minor" managers. The web version should have similar behavior: only major managers should be shown at the top level

A "major" manager is one with identical major and minor components. e.g. `ActiveSurface.ActiveSurface` is major, while `ActiveSurface.ActiveSurfaceServo` is a minor manager within `ActiveSurface`

So, for this manager the tree would look like:

- ActiveSurface.ActiveSurface
    - ActiveSurface.ActiveSurfaceServo

**Comment by tchamberlin** [comment]
Also, convert `<p>` tags to `<li>`, inside of a `<ul>`. To avoid bullet points from being rendered, set a class on the `<ul>`:

```html
<ul class="list-unstyled">
   <li>...</li>
</ul>
```

https://getbootstrap.com/docs/5.3/content/typography/#unstyled

**Comment by sofiarobertson** [comment]
commit a4b140467ef8fae1b125693755e58ecbe0634db5
