### ISSUE TITLE
Manager tree should display only minor manager name

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/cleo_web#8]
In #7 you introduced the tree structure. Now let's refine this even more: instead of showing the "full" Manager name, items in the tree should only show the minor component

So you'd have something like

- ActiveSurface
    - ActiveSurfaceServo

instead of

- ActiveSurface.ActiveSurface
    - ActiveSurface.ActiveSurfaceServo

Ensure that managers can still be selected, and that the `manager` URL parameter still works as it did before

**Comment by sofiarobertson** [comment]
commit ebc5bab2f391a623a417746559dcd4c4d8eab3b4
