### ISSUE TITLE
Add Samplers to Device Explorer

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/cleo_web#9]
Currently the Device Explorer shows only information about _Parameters_. Now you will need to include _Samplers_. This will result in two new columns in your Device Explorer

For reference, here is a screenshot:

![Image](https://github.com/GreenBankObservatory/cleo_web/assets/2555049/7bde80aa-32f7-45aa-abb1-00c437e3cde8)

**Comment by tchamberlin** [comment]
For this task, please make all your commits on a new branch, e.g. `devex_samplers`. You will use this new branch as the basis for a Pull Request. This will allow us to better track the code that written to complete this issue

**Comment by sofiarobertson** [comment]
commit 57cbb67c69f3f908b083e802e078918ed1ad1dbb
